---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::r-base==4.4.3
  - conda-forge::r-optparse==1.7.5
  - conda-forge::r-dplyr==1.2.0
  - conda-forge::r-arrow==23.0.0
