---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::polars=1.36.1
  - conda-forge::matplotlib=3.10.8
  - bioconda::tabix=1.11
