---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::python==3.14.3
  - conda-forge::polars==1.38.1
  - conda-forge::tqdm==4.67.3
